consul:
  build: .
  dockerfile: Dockerfile
  ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400
    - 8500:8500
    - 53:53
    - 53:53/udp
  volumes:
    - ./config:/consul_config/
  command:
    consul agent -server -config-dir=/consul_config/  
