mesosmaster:
  image: asdfsx/mesos-master:0.24.1
  net: host
  environment:
    - MESOS_HOSTNAME_LOOKUP=false
    - MESOS_IP=0.0.0.0
    - MESOS_QUORUM=1
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_WORK_DIR=/tmp/mesos
  volumes:
    - /tmp/mesos:/tmp/mesos
