marathon:
  image: mesoscloud/marathon
  ports:
    - 7070:7070
  environment:
    - MARATHON_HTTP_PORT=7070
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_ZK=zk://zookeeper:2181/marathon
